language: node_js

cache:
  yarn: true

node_js:
  - "8"
  - "10"
  - "11"

# TODO: Test each relay-compiler version compatible with
env:
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - yarn remove webpack
  - yarn add webpack@$WEBPACK_VERSION

script:
  - yarn build
  - yarn clean
  - yarn relay-compile