language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "10"
  - "12"
  - "14"
  - "15"
  - "16"

# TODO: Test each relay-compiler version compatible with
env:
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4
  - WEBPACK_VERSION=5

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - yarn remove webpack
  - yarn add webpack@$WEBPACK_VERSION

script:
  - yarn build
  - yarn clean
  - yarn relay-compile
